    - name: Download Filebeat deb
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-amd64.deb"
        dest: "/tmp/filebeat-{{ elk_stack_version }}-amd64.deb"
      register: download_filebeat
      until: download_filebeat is succeeded
    - name: Install Filebeat
      become: true
      apt:
        deb: "/tmp/filebeat-{{ elk_stack_version }}-amd64.deb"
        state: present
    - name: Install sysvinit-utils
      become: true
      apt:
        name: sysvinit-utils
        state: present
