---
# tasks file for filebeat-role
    - include_tasks: "filebeat_{{ ansible_facts.pkg_mgr }}_tasks.yml"
    - name: Configure Filebeat
      become: true
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: 0644
      notify: restart Filebeat
    - name: Set Filebeat systemwork
      become: true
      command:
        cmd: filebeat modules enable system
        chdir: /usr/share/filebeat/bin
      register: myoutput1
      changed_when: myoutput1.rc != 0
    - name: Load Kibana dashboard
      become: true
      command:
        cmd: filebeat setup
        chdir: /usr/share/filebeat/bin
      register: filebeat_setup
      until: filebeat_setup is succeeded
      notify: restart Filebeat
